config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :homeworks
  resources :categories
  get 'welcome/index'
  get 'welcome/next'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 4 }
  #attributes name harus diisi minial 4 char
  has_many :homeworks
end

app/models/homework.rb
class Homework < ApplicationRecord
  default_scope { order("homework_name") }
  # scope dengan argumen
  # scope :created_before, ->(time) { where("created_at < ?", time) }
  # penggunannya di controller tinggal Homework.created_before(Time.zone.now)

  validates :homework_name, presence: true
  validates :category, presence: true
  validates :deadline, presence: true
  validates :description, presence: true, length: { maximum: 300 }
  validate :deadline_cannot_be_in_the_past
  belongs_to :category

  #contoh custom validation
  def deadline_cannot_be_in_the_past
    errors.add(:deadline, "can't be in the past!") if
      deadline < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    respond_to do |format|
      if @category.save
        format.html { redirect_to "/categories/new", notice: "Category success created!" }
      else
        format.html { redirect_to "/categories/new", notice: "Category wasn't success created." }
      end
    end
  end

  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(params.require(:category).permit(:name))
        format.html { redirect_to categories_path, notice: "Category was updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: "Categories was deleted." }
    end
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_categories, only: [:new, :edit, :update, :create]
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: "Homework was successfully created." }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: "Homework was successfully updated." }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: "Homework was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_homework
    @homework = Homework.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def homework_params
    params.require(:homework).permit(:homework_name, :category, :deadline, :description)
  end

  def set_categories
    @category = Category.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def next
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= render 'navigation'%>
<%= form_with(model: category, local:true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/categories/_navigation.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<ul class="nav">
  <li class="active"><%= link_to 'Homework', homeworks_path, :class => 'navbar-link' %>
  <li class="active"><%= link_to 'Category', categories_path, :class => 'navbar-link' %>
  </li>
</ul>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render 'navigation'%>
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Homeworks Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/homeworks/_form.html.erb
<%= form_with(model: homework, local: true) do |form| %>
<% if homework.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

  <ul>
    <% homework.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :homework_name %>
  <%= form.text_area :homework_name, id: :homework_homework_name %>
</div>

<div class="field">
  <%= form.label :category %>
  <% if @homework.category.present? %>
  <%= select_tag 'homework[category_id]', options_for_select(@category.collect { |c| [c.name, c.id] }, {:selected => @homework.category.id}) %>
  <% else %>
  <%= select_tag 'homework[category_id]', options_for_select(@category.collect { |c| [c.name, c.id] }) %>
  <% end %>
</div>

<div class="field">
  <%= form.label :deadline %>
  <%= form.date_select :deadline, id: :homework_deadline %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :homework_description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/homeworks/_navigation.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<ul class="nav">
  <li class="active"><%= link_to 'Homework', homeworks_path, :class => 'navbar-link' %>
  <li class="active"><%= link_to 'Category', categories_path, :class => 'navbar-link' %>
  </li>
</ul>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<%= render 'navigation'%>

<p id="notice"><%= notice %></p>

<h1>Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Homework name</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.homework_name %></td>
        <td><%= homework.category %></td>
        <td><%= homework.deadline %></td>
        <td><%= homework.description %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Homework name:</strong>
  <%= @homework.homework_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @homework.category %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @homework.deadline %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homework.description %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<div>asw</div>

app/views/welcome/next.html.erb
<h1>ini dari next </h1>